name: Sync from WildKernels
on: workflow_dispatch

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dusfff
        uses: actions/checkout@v5
        with:
          ref: GOOO
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}l

      - name: Sync from WildKernels main
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote add wild https://github.com/ahmed-alnassif/GKI_KernelSU_SUSFS.git
          git fetch wild dev
          git reset --hard wild/dev
          git push origin GOOO --force
