name: Custom GKI Kernels

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Choose Release Type'
        required: true
        type: choice
        options:
          - Pre-Release
          - Release
        default: Release   
      kernel_build:
        description: |
          Comma-separated list of kernels to build: a12-5.10,a13-5.10,a13-5.15,a14-5.15,a14-6.1,a15-6.6
          or "all" to build every kernel.
        required: true
        type: string
        default: a
      kernel_uname:
        description: 'Custom kernel version name (Ex: Characters after 5.10.198 or leave blank to use default kernel version uname)'
        required: false
        type: string
      kernel_variant:
        description: 'Choose KernelSU Variant'
        required: true
        type: choice
        options:
          - WKSU
          - KSU
          - NEXT
          - SukiSU
          - MKSU
        default: NEXT
      kernelsu_branch:
        description: "Choose ksu branch"
        required: true
        type: choice
        options:
          - Stable
          - Dev
          - Other
        default: Dev
      kernelsu_branch_other:
        description: "If 'Other' is selected, specify your custom branch"
        required: false
        type: string
        default: ""  
        
jobs:
  build-kernels-a12-5-10:
    name: ${{ inputs.kernel_variant }}-Android_12-5.10
    if: contains(github.event.inputs.kernel_build, 'all') || contains(github.event.inputs.kernel_build, 'a12-5.10')
    uses: ./.github/workflows/kernel-a12-5-10.yml
    secrets: inherit
    with:
      kernel_variant: ${{ inputs.kernel_variant }}
      kernel_uname: ${{ inputs.kernel_uname }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}

  build-kernels-a13-5-10:
    name: ${{ inputs.kernel_variant }}-Android_13-5.10
    if: contains(github.event.inputs.kernel_build, 'all') || contains(github.event.inputs.kernel_build, 'a13-5.10')
    uses: ./.github/workflows/kernel-a13-5-10.yml
    secrets: inherit
    with:
      kernel_variant: ${{ inputs.kernel_variant }}
      kernel_uname: ${{ inputs.kernel_uname }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}
      
  build-kernels-a13-5-15:
    name: ${{ inputs.kernel_variant }}-Android_13-5.15
    if: contains(github.event.inputs.kernel_build, 'all') || contains(github.event.inputs.kernel_build, 'a13-5.15')
    uses: ./.github/workflows/kernel-a13-5-15.yml
    secrets: inherit
    with:
      kernel_variant: ${{ inputs.kernel_variant }}
      kernel_uname: ${{ inputs.kernel_uname }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}

  build-kernels-a14-5-15:
    name: ${{ inputs.kernel_variant }}-Android_14-5.15
    if: contains(github.event.inputs.kernel_build, 'all') || contains(github.event.inputs.kernel_build, 'a14-5.15')
    uses: ./.github/workflows/kernel-a14-5-15.yml
    secrets: inherit
    with:
      kernel_variant: ${{ inputs.kernel_variant }}
      kernel_uname: ${{ inputs.kernel_uname }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}

  build-kernels-a14-6-1:
    name: ${{ inputs.kernel_variant }}-Android_14-6.1
    if: contains(github.event.inputs.kernel_build, 'all') || contains(github.event.inputs.kernel_build, 'a14-6.1')
    uses: ./.github/workflows/kernel-a14-6-1.yml
    secrets: inherit
    with:
      kernel_variant: ${{ inputs.kernel_variant }}
      kernel_uname: ${{ inputs.kernel_uname }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}

  build-kernels-a15-6-6:
    name: ${{ inputs.kernel_variant }}-Android_15-6.6
    if: contains(github.event.inputs.kernel_build, 'all') || contains(github.event.inputs.kernel_build, 'a15-6.6')
    uses: ./.github/workflows/kernel-a15-6-6.yml
    secrets: inherit
    with:
      kernel_variant: ${{ inputs.kernel_variant }}
      kernel_uname: ${{ inputs.kernel_uname }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}
