name: Build GKI Kernel
permissions:
  contents: write
  actions: write 

on:
  workflow_dispatch:
    inputs:
      android_version:
        description: 'Android Version'
        required: true
        default: 'android14'
        type: choice
        options:
          - android12
          - android13
          - android14
          - android15
      kernel_version:
        description: 'Kernel Version'
        required: true
        default: '6.1'
        type: choice
        options:
          - '5.10'
          - '5.15'
          - '6.1'
          - '6.6'
      sub_level:
        description: 'Sub Level'
        required: true
        default: '138'
        type: string
      os_patch_level:
        description: 'OS Patch Level'
        required: true
        default: '2024-11'
        type: string
      revision:
        description: 'Revision (for Android 12 only)'
        required: false
        default: 'r1'
        type: string

jobs:
  build-gki:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      USE_CCACHE: "true"

    steps:
      - name: Maximize Build Space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-swapfile: 'true'
          remove-cached-tools: 'false'
          verbose: 'true'
          
      - name: Set Environment Variables
        run: |
          echo "KBUILD=/home/runner/work/kernel_akita" >> $GITHUB_ENV
          echo "KERNEL_BUILDS=/home/runner/work/kernel_builds" >> $GITHUB_ENV
          echo "CONFIG=${{ inputs.android_version }}-${{ inputs.kernel_version }}-${{ inputs.sub_level }}" >> $GITHUB_ENV
          
          # Create build directories
          mkdir -p /home/runner/work/kernel_builds/${{ inputs.kernel_version }}.${{ inputs.sub_level }}
          
          # Set timestamp function
          echo "TIMESTAMP=$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ccache git curl unzip zip python3 python3-pip build-essential bc bison flex libssl-dev libelf-dev
          
          # Install repo tool
          mkdir -p ~/.local/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.local/bin/repo
          chmod a+rx ~/.local/bin/repo
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Set up ccache
        run: |
          mkdir -p ~/.cache/bazel
          ccache --version
          ccache --max-size=4G
          ccache --set-config=compression=true
          echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV

      - name: Download toolchain
        run: |
          AOSP_MIRROR=https://android.googlesource.com
          BRANCH=main-kernel-build-2024
          git clone $AOSP_MIRROR/kernel/prebuilts/build-tools -b $BRANCH --depth 1 kernel-build-tools
          git clone $AOSP_MIRROR/platform/system/tools/mkbootimg -b $BRANCH --depth 1 mkbootimg

      - name: Set environment variables for tools
        run: |
          echo "AVBTOOL=$GITHUB_WORKSPACE/kernel-build-tools/linux-x86/bin/avbtool" >> $GITHUB_ENV
          echo "MKBOOTIMG=$GITHUB_WORKSPACE/mkbootimg/mkbootimg.py" >> $GITHUB_ENV
          echo "UNPACK_BOOTIMG=$GITHUB_WORKSPACE/mkbootimg/unpack_bootimg.py" >> $GITHUB_ENV

      - name: Set boot sign key
        env:
          BOOT_SIGN_KEY: ${{ secrets.BOOT_SIGN_KEY }}
        run: |
          if [ ! -z "$BOOT_SIGN_KEY" ]; then
            echo "$BOOT_SIGN_KEY" > ./kernel-build-tools/linux-x86/share/avb/testkey_rsa2048.pem
            echo "BOOT_SIGN_KEY_PATH=$GITHUB_WORKSPACE/kernel-build-tools/linux-x86/share/avb/testkey_rsa2048.pem" >> $GITHUB_ENV
          else
            echo "BOOT_SIGN_KEY is not set. Using AOSP sign key..."
            echo "BOOT_SIGN_KEY_PATH=$GITHUB_WORKSPACE/kernel-build-tools/linux-x86/share/avb/testkey_rsa2048.pem" >> $GITHUB_ENV
          fi

      - name: Clean old files and clone dependencies
        run: |
          echo "Removing old files and folders..."
          rm -rf susfs4ksu kernel_patches AnyKernel3-p8a common bootimgs
          
          echo "Cloning SuSFS, Wild patches, AnyKernel3 and other dependencies..."
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}
          git clone https://github.com/infectedmushi/kernel_patches -b main
          git clone https://github.com/deepongi-labs/AnyKernel3-p8a -b gki-2.0

      - name: Initialize and Sync Kernel Source
        run: |
          echo "Repo init and sync..."
          FORMATTED_BRANCH="${{ inputs.android_version }}-${{ inputs.kernel_version }}-${{ inputs.os_patch_level }}"
          
          repo init --depth=1 --u https://android.googlesource.com/kernel/manifest -b common-${FORMATTED_BRANCH}
          
          # Check for deprecated branch
          REMOTE_BRANCH=$(git ls-remote https://android.googlesource.com/kernel/common ${FORMATTED_BRANCH} || echo "")
          DEFAULT_MANIFEST_PATH=.repo/manifests/default.xml
          if echo "$REMOTE_BRANCH" | grep -q "deprecated"; then
            echo "Found deprecated branch: $FORMATTED_BRANCH"
            sed -i "s/\"${FORMATTED_BRANCH}\"/\"deprecated\/${FORMATTED_BRANCH}\"/g" $DEFAULT_MANIFEST_PATH
          fi
          
          repo --trace sync -c -j$(nproc --all) --no-tags --fail-fast

      - name: Add KSU-Next
        run: |
          echo "Entering kernel directory..."
          cd common
          echo "Adding KSU-Next..."
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next

      - name: Apply SUSFS patches
        run: |
          echo "Applying SUSFS patches..."
          cd common
          
          # Copy SUSFS patches
          cp -v ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch ./
          cp -v ../susfs4ksu/kernel_patches/fs/* ./fs/
          cp -v ../susfs4ksu/kernel_patches/include/linux/* ./include/linux/
          
          # Apply main SUSFS patch
          patch -p1 --forward --fuzz=3 < 50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch
          
          # Apply KSU-Next specific patches
          cd ./KernelSU-Next
          cp -v ../../kernel_patches/next/0001-kernel-implement-susfs-v1.5.8-KernelSU-Next-v1.0.8.patch ./
          patch -p1 --fuzz=3 < 0001-kernel-implement-susfs-v1.5.8-KernelSU-Next-v1.0.8.patch
          
          # Apply additional KSU-Next fix
          curl -Ls "https://github.com/cvnertnc/KernelSU-Next/commit/6a7707dc38fc9217dbdc79fe471220383dec2369.patch" | patch -p1 --fuzz=3
          
          cd ..

      - name: Apply additional patches
        run: |
          cd common
          
          echo "Applying more hide stuff and manual hooks patch..."
          cp -v ../kernel_patches/69_hide_stuff.patch ./
          patch -p1 -F 3 < 69_hide_stuff.patch
          
          echo "Removing exports..."
          sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' ./BUILD.bazel
          rm -v android/abi_gki_protected_exports_* || true

      - name: Add configuration settings
        run: |
          echo "Adding KSU configuration settings to gki_defconfig..."
          
          # KSU settings
          echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_KPROBES_HOOK=n" >> ./common/arch/arm64/configs/gki_defconfig
          
          # SUSFS settings
          echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./common/arch/arm64/configs/gki_defconfig
          
          # Additional tmpfs config
          echo "CONFIG_TMPFS_XATTR=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./common/arch/arm64/configs/gki_defconfig
          
          # Additional network config
          echo "CONFIG_IP_NF_TARGET_TTL=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP6_NF_TARGET_HL=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP6_NF_MATCH_HL=y" >> ./common/arch/arm64/configs/gki_defconfig
          
          # BBR Config
          echo "CONFIG_TCP_CONG_ADVANCED=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TCP_CONG_BBR=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_NET_SCH_FQ=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TCP_CONG_BIC=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TCP_CONG_WESTWOOD=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TCP_CONG_HTCP=n" >> ./common/arch/arm64/configs/gki_defconfig

      - name: Modify kernel build settings
        run: |
          echo "Modifying kernel build settings..."
          
          # Modify setlocalversion
          sed -i '$s|echo "\$res"|echo "\$res-TheFloresto+"|' ./common/scripts/setlocalversion
          
          # Modify stamp.bzl
          sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
          
          # Remove check_defconfig
          sed -i '2s/check_defconfig//' ./common/build.config.gki
          
          # Set build timestamp
          sed -i "s|build-timestamp = \$(or \$(KBUILD_BUILD_TIMESTAMP), \$(build-timestamp-auto))|build-timestamp = \"$(date -u +"%a %b %d %T UTC %Y")\"|" ./common/init/Makefile

      - name: Build kernel
        run: |
          echo "Building kernel..."
          
          # Build with Bazel
          if [ "${{ inputs.android_version }}" == "android14" ] || [ "${{ inputs.android_version }}" == "android15" ]; then
            tools/bazel build --config=fast --lto=thin //common:kernel_aarch64_dist
          else
            # For older versions, try alternative build method
            tools/bazel build --config=fast --lto=thin //common:kernel_aarch64_dist
          fi
          
          echo "Kernel build completed!"
          ccache --show-stats

      - name: Copy kernel images
        run: |
          echo "Copying Images..."
          mkdir -p bootimgs
          
          if [ "${{ inputs.android_version }}" == "android14" ] || [ "${{ inputs.android_version }}" == "android15" ]; then
            # For Android 14/15 with Bazel
            cp -v ./bazel-bin/common/kernel_aarch64/Image.lz4 ./bootimgs/Image.lz4
            cp -v ./bazel-bin/common/kernel_aarch64/Image.gz ./bootimgs/Image.gz || gzip -c ./bazel-bin/common/kernel_aarch64/Image > ./bootimgs/Image.gz
            cp -v ./bazel-bin/common/kernel_aarch64/Image ./bootimgs/Image
            
            # Try to copy boot images if they exist
            cp -v ./bazel-bin/common/kernel_aarch64_gki_artifacts/boot.img ./bootimgs/boot.img || echo "boot.img not found"
            cp -v ./bazel-bin/common/kernel_aarch64_gki_artifacts/boot-gz.img ./bootimgs/boot-gz.img || echo "boot-gz.img not found"
            cp -v ./bazel-bin/common/kernel_aarch64_gki_artifacts/boot-lz4.img ./bootimgs/boot-lz4.img || echo "boot-lz4.img not found"
          else
            # For older Android versions
            cp -v ./out/${{ inputs.android_version }}-${{ inputs.kernel_version }}/dist/Image ./bootimgs/Image
            cp -v ./out/${{ inputs.android_version }}-${{ inputs.kernel_version }}/dist/Image.lz4 ./bootimgs/Image.lz4
            gzip -c ./bootimgs/Image > ./bootimgs/Image.gz
          fi

      - name: Create AnyKernel3 ZIP files
        run: |
          echo "Creating ZIP for kernel image..."
          
          # Set ZIP names with timestamp
          export ZIP_NAME_LZ4="AK3-A${{ inputs.android_version }}-${{ inputs.kernel_version }}.${{ inputs.sub_level }}-KSUN-LZ4-${TIMESTAMP}.zip"
          export ZIP_NAME_GZ="AK3-A${{ inputs.android_version }}-${{ inputs.kernel_version }}.${{ inputs.sub_level }}-KSUN-GZ-${TIMESTAMP}.zip"
          export ZIP_NAME_RAW="AK3-A${{ inputs.android_version }}-${{ inputs.kernel_version }}.${{ inputs.sub_level }}-KSUN-RAW-${TIMESTAMP}.zip"
          
          # Create LZ4 ZIP
          cd AnyKernel3-p8a
          mv ../bootimgs/Image.lz4 ./Image.lz4
          zip -r "$ZIP_NAME_LZ4" ./*
          mv "$ZIP_NAME_LZ4" ../$ZIP_NAME_LZ4
          rm -f ./Image.lz4
          cd ..
          echo "AK3 LZ4 zip done!"
          
          # Create GZ ZIP
          cd AnyKernel3-p8a
          mv ../bootimgs/Image.gz ./Image.gz
          zip -r "$ZIP_NAME_GZ" ./*
          mv "$ZIP_NAME_GZ" ../$ZIP_NAME_GZ
          rm -f ./Image.gz
          cd ..
          echo "AK3 GZ zip done!"
          
          # Create RAW ZIP
          cd AnyKernel3-p8a
          mv ../bootimgs/Image ./Image
          zip -r "$ZIP_NAME_RAW" ./*
          mv "$ZIP_NAME_RAW" ../$ZIP_NAME_RAW
          rm -f ./Image
          cd ..
          echo "AK3 RAW zip done!"

      - name: Create boot images (if available)
        run: |
          if [ -f "./bootimgs/boot.img" ]; then
            export BUILD_IMG="A${{ inputs.android_version }}-${{ inputs.kernel_version }}.${{ inputs.sub_level }}-KSUN-RAW-${TIMESTAMP}.img"
            export BUILD_IMG_GZ="A${{ inputs.android_version }}-${{ inputs.kernel_version }}.${{ inputs.sub_level }}-KSUN-GZ-${TIMESTAMP}.img"
            export BUILD_IMG_LZ4="A${{ inputs.android_version }}-${{ inputs.kernel_version }}.${{ inputs.sub_level }}-KSUN-LZ4-${TIMESTAMP}.img"
            
            cp ./bootimgs/boot.img ./$BUILD_IMG
            cp ./bootimgs/boot-gz.img ./$BUILD_IMG_GZ 2>/dev/null || echo "boot-gz.img not available"
            cp ./bootimgs/boot-lz4.img ./$BUILD_IMG_LZ4 2>/dev/null || echo "boot-lz4.img not available"
          else
            echo "Boot images not available, creating them manually..."
            
            # Create boot images manually using mkbootimg
            cd bootimgs
            
            # Create gzip version if not exists
            if [ ! -f "Image.gz" ]; then
              gzip -c Image > Image.gz
            fi
            
            echo "Building boot.img"
            $MKBOOTIMG --header_version 4 --kernel Image --output boot.img
            $AVBTOOL add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot.img --algorithm SHA256_RSA2048 --key $BOOT_SIGN_KEY_PATH
            
            echo "Building boot-gz.img"
            $MKBOOTIMG --header_version 4 --kernel Image.gz --output boot-gz.img
            $AVBTOOL add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot-gz.img --algorithm SHA256_RSA2048 --key $BOOT_SIGN_KEY_PATH
            
            echo "Building boot-lz4.img"
            $MKBOOTIMG --header_version 4 --kernel Image.lz4 --output boot-lz4.img
            $AVBTOOL add_hash_footer --partition_name boot --partition_size $((64 * 1024 * 1024)) --image boot-lz4.img --algorithm SHA256_RSA2048 --key $BOOT_SIGN_KEY_PATH
            
            # Copy to parent directory with proper names
            export BUILD_IMG="A${{ inputs.android_version }}-${{ inputs.kernel_version }}.${{ inputs.sub_level }}-KSUN-RAW-${TIMESTAMP}.img"
            export BUILD_IMG_GZ="A${{ inputs.android_version }}-${{ inputs.kernel_version }}.${{ inputs.sub_level }}-KSUN-GZ-${TIMESTAMP}.img"
            export BUILD_IMG_LZ4="A${{ inputs.android_version }}-${{ inputs.kernel_version }}.${{ inputs.sub_level }}-KSUN-LZ4-${TIMESTAMP}.img"
            
            cp boot.img ../$BUILD_IMG
            cp boot-gz.img ../$BUILD_IMG_GZ
            cp boot-lz4.img ../$BUILD_IMG_LZ4
            
            cd ..
          fi

      - name: Compress all img files
        run: |
          echo "Compressing all img files..."
          for image in *.img; do
            if [ -f "$image" ]; then
              gzip -vnf9 "$image"
            fi
          done

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: KSUN-${{ inputs.android_version }}-${{ inputs.kernel_version }}.${{ inputs.sub_level }}-${{ env.TIMESTAMP }}
          path: |
            *.zip
            *.img.gz
            bootimgs/Image*
          retention-days: 7

      - name: Show build summary
        run: |
          echo "Build completed successfully!"
          echo "Build artifacts:"
          ls -la *.zip *.img.gz 2>/dev/null || echo "No final artifacts found"
          echo "Boot images:"
          ls -la bootimgs/ 2>/dev/null || echo "No bootimgs directory"
          echo "Disk usage:"
          df -h
          echo "ccache stats:"
          ccache --show-stats
